name = "cardano-template-and-ecosystem-monitoring/aiken"
version = "0.0.0"
compiler = "v1.1.21"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'cardano-template-and-ecosystem-monitoring/aiken'"

[repository]
user = "cardano-template-and-ecosystem-monitoring"
project = "aiken"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.0.0"
source = "github"

[[dependencies]]
name = "sidan-lab/vodka"
version = "0.1.15"
source = "github"

[config]
