name = "cardano-foundation/cardano-template-and-ecosystem-monitoring"
version = "0.0.0"
compiler = "v1.1.19"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'cardano-foundation/cardano-template-and-ecosystem-monitoring'"

[repository]
user = "cardano-foundation"
project = "cardano-template-and-ecosystem-monitoring"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.0.0"
source = "github"

[[dependencies]]
name = "sidan-lab/vodka"
version = "0.1.22"
source = "github"

[config]
