name = "iot-sentinel/storage"
version = "0.0.1"
license = "Apache-2.0"
description = "IoT Sentinel - 3-Phase Distribution Transformer Monitoring System for Cardano"

[repository]
user = "cardano-foundation"
project = "cardano-template-and-ecosystem-monitoring"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[config.default]
network_id = 41
